# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 34077937fa493984d1ebe56d0bec482f0a983dfde7babbf13e64375b526a598ac1739134736c9b309df896bb3c7d63f7d8f993c8e7c64d7038cef032231d029d

test:
  secret_key_base: 7ebd4fff7f7e1607cd2b89fc4aed20ae669bb978b89312880d1d9a05123db3536627dac1d9375321cbd33895c035f5e4b2fc7b3f2031c6d454223e80f70fd141

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
